### ISSUE TITLE
Object is possibly 'undefined'.

### ISSUE THREAD

**Issue by queejie** [slavede/ngx-paginate#16] opened 2019-04-08 16:07 UTC
Thanks for this module!

I'm unable to include it in my project, which is using Angular 7 and Typescript 3.2.4.
`ERROR in node_modules/ngx-paginate/ngx-paginate.d.ts.ɵa.html(2,9): : Object is possibly 'undefined'.`

**Comment by slavede** [comment] 2019-04-09 14:05
How are you trying to import it?

**Comment by slavede** [comment] 2019-04-23 15:08
Closing for being unresponsive and unable to reproduce

**Closed by slavede** 2019-04-23 15:08 UTC
Labels: more-info-needed
